enum DataSource {
  success,
  noContent,
  badRequest,
  forbidden,
  unauthorized,
  internalServerError,
  connectionTimeout,
  cancelled,
  receiveTimeout,
  sendTimeout,
  cacheError,
  notInternetConnection,
  defaultError,
}
