name: melos_app

packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.6.1
      flutter: ">=1.17.0"

    dependencies:
      cupertino_icons: ^1.0.8
      dio: ^5.8.0+1
      pretty_dio_logger: ^1.4.0
      json_annotation: ^4.9.0
      dartz: ^0.10.1
      connectivity_plus: ^6.1.4
      go_router: ^16.0.0
      retrofit: ^4.4.2
      flutter_bloc: ^9.1.1
      flutter_secure_storage: ^9.2.4
      rive: ^0.13.20
      intl: ^0.20.2

    dev_dependencies:
      retrofit_generator: ^9.2.0
      flutter_lints: ^5.0.0
      json_serializable: ^6.9.5
      build_runner: ^2.4.15

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  test:
    run: melos exec --concurrency=1 -- flutter test
  update: melos exec flutter pub outdated
  upgrade: melos exec flutter pub upgrade --major-versions
