name: melos_test

packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.6.1
      flutter: ">=1.17.0"
      
    dependencies:
      melos: ^6.3.2
      cupertino_icons: ^1.0.8
    
    dev_dependencies:
      flutter_lints: ^5.0.0

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  test:
    run: melos exec --concurrency=1 -- flutter test
  update: melos exec flutter pub outdated
  upgrade: melos exec flutter pub upgrade --major-versions